name: CD AWS

on:
  workflow_run: # Define o trigger para quando um workflow rodar
    workflows: ["CI"] # Define o nome do workflow que deve ser monitorado
    types: [completed] # Faz o trigger somente quando o status tiver sido concluido    
    branches: [main] # Só quando for pra branch main

jobs:
  deploy:
    name: Deploy to AWS ECS Fargate
    runs-on: ubuntu-latest
    environment: Production
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # define que esse job só ira rodar se o workflow anterior for concluido com sucesso
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-east-1

      - name: Login at Amazon ECR
        id: login-ecr # Precisaremos da informacao desses step
        uses: aws-actions/amazon-ecr-login@v2
          
      - name: Download Task Definition
        # aws ecs describe-task-definition - pega a definição atual
        # --task-definition client-api-task - nome da task definition (vamos criar depois na AWS)
        # --query taskDefinition - extrai só a parte que interessa
        # > task-definition.json - salva em arquivo
        run: |
          aws ecs describe-task-definition \
          --task-definition client-api-task \
          --query taskDefinition \
          > task-definition.json
          
      - name: Update Task Definition Image
        id: task-definition # identificador do step pois vamos precisar da saída desse step
        uses: aws-actions/amazon-ecs-render-task-definition@v1 # action oficial da AWS
        with:
          task-definition: task-definition.json # arquivo que baixamos no step anterior
          container-name: client-api # nome do container dentro da Task Definition
          image: ${{ steps.login-ecr.outputs.registry }}/dotnet/client-api:latest # nova imagem para usar (a que publicamos no CI)
          
      - name: Deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2 # action oficial da AWS para deploy
        with:
          task-definition: ${{ steps.task-definition.outputs.task-definition }} # usa a saída do step anterior (o JSON atualizado)
          service: client-api-service # nome do Service no ECS
          cluster: prd-worthix-dotnet # nome do Cluster no ECS
          wait-for-service-stability: true # espera o deploy terminar antes de concluir o workflow